account/urls.py
"""Defines URL patterns for vareaze."""

from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
	# Home page
	path('register/', views.register, name='register'),
	path('logout/', views.logged_out, name='logged_out'),
	path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
]

unicorn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('vareaze.urls')),
]

vareaze/urls.py
"""Defines URL patterns for vareaze."""

from django.urls import path

from . import views

app_name = 'vareaze'
urlpatterns = [
	# Home page
	path('', views.home, name='home'),
	path('contract/<int:user_id>/', views.initiate, name='initiate'),
	path('profile/<int:user_id>/', views.profile, name='profile'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import string
import random

# Create your models here.
class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, first_name, last_name, password=None):
		if not email:
			raise ValueError("Users must have a valid email.")
		if not username:
			raise ValueError("Users must have a username.")
		if not first_name:
			raise ValueError("Users must enter a first name.")
		if not last_name:
			raise ValueError("Users must enter a last name.")

		user = self.model(
			email = self.normalize_email(email),
			username=username,
			first_name=first_name,
			last_name=last_name
			)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, first_name, last_name, password):
		user = self.create_user(
			email = self.normalize_email(email),
			password=password,
			username=username,
			first_name=first_name,
			last_name=last_name,
			)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user



class Account(AbstractBaseUser):
	"""Generate vareaze ID"""
	def vareaze_id_generator(size=12, chars=string.ascii_uppercase + string.digits):
		return ''.join(random.choice(chars) for _ in range(size))
	email = models.EmailField(verbose_name='email', max_length=60, unique=True)
	username = models.CharField(max_length=30, unique=True)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	date_joined = models.DateTimeField(verbose_name='date_joined', auto_now_add=True)
	last_login = models.DateTimeField(verbose_name='last_login', auto_now_add=True)
	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)
	is_staff = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)
	vareaze_id = models.CharField(
		max_length = 10,
		blank=True,
		editable=False,
		unique=True,
		default=vareaze_id_generator(),
		)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

	objects = MyAccountManager()

	def __str__(self):
		return self.email

	def has_perm(self, perm, obj=None):
		return self.is_admin

	def has_module_perms(self, app_label):
		return True

vareaze/models.py
from django.db import models
from account.models import Account
from datetime import datetime
from pytz import timezone

est_tz = timezone('EST')
tz_format = "%Y-%m-%d"
# Create your models here.
class Contract(models.Model):
	"""An agreement between two users"""
	owner = models.ForeignKey(Account, on_delete = models.PROTECT)
	date_added = models.DateTimeField(default=datetime.now(est_tz).strftime("%Y-%m-%d"))
	vareaze_id = models.CharField(max_length=12)
	sent_to = models.CharField(max_length=12)

	def __str__(self):
		# String representation
		return f"Contract initiated: {str(self.date_added)[:10]} with {self.sent_to}"

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import Account

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=60, help_text="Enter valid email address.")

	class Meta:
		model = Account
		fields = ("email", "username", "first_name", "last_name", "password1", "password2")
		
class AuthenticateUserForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	
	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

	

vareaze/forms.py
from django import forms
from .models import Contract

class ContractForm(forms.ModelForm):
	expiration_date = forms.DateField(widget= forms.SelectDateWidget)
	class Meta:
		model = Contract
		fields = ['expiration_date', 'vareaze_id', 'sent_to']
		labels = {
			'expiration_date': 'Expiration Date',
			'vareaze_id': 'Vareaze ID',
			'sent_to': 'Other Party',
		}

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm, AuthenticateUserForm



# Create your views here.
def register(request):
	context = {}
	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			email = form.cleaned_data.get('email')
			raw_password = form.cleaned_data.get('password')
			account = authenticate(email=email, password=raw_password)
			login(request, user)
			return redirect('vareaze:home')
		else:
			context['registration_form'] = form
	else:
		form = RegistrationForm()
		context['registration_form'] = form

	return render(request, 'account/register.html', context)

def authenticate_user(request):
	context= {}
	user = request.user
	if user.is_authenticated:
		return redirect('vareaze:home')

	if request.POST:
		form = AuthenticateUserForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				return redirect('vareaze:home')
	else:
		form = AuthenticateUserForm()

	context['authenticate_form'] = form
	return render(request, 'account/authenticate_user.html', context)

def logged_out(request):
	logout(request)
	return render(request, 'account/logged_out.html')

vareaze/views.py
from django.shortcuts import render, redirect
from .models import Contract
from account.models import Account
from .forms import ContractForm


# Create your views here.
def home(request):
	"""The home page"""
	user = request.user
	accounts = Account.objects.all()
	context = {'accounts':accounts, 'user':user}
	return render(request, 'vareaze/home.html', context)

def initiate(request, user_id):
	"""List user contracts"""
	contracts = Contract.objects.all()
	user_vareaze_id = request.user.vareaze_id
	account_list = Account.objects.all()
	owner = Account.objects.get(id=user_id)
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = ContractForm()
	else:
		print(request.POST)
		form = ContractForm(data=request.POST)
		if form.is_valid():
			if request.POST.get('vareaze_id') == user_vareaze_id:
				contract = form.save(commit=False)
				contract.owner = owner
				contract.save()
				return redirect('vareaze:home')
			else:
				return "Invalid Pin"
		else:
			return redirect('vareaze:initiate', user_id)
	context = {'contracts':contracts, 'owner':owner, 'form':form, 'account_list':account_list}
	return render(request, 'vareaze/contract.html', context)

def profile(request, user_id):
	user = Account.objects.get(id=user_id)
	contracts = Contract.objects.all()
	context = {'user':user, 'contracts': contracts}
	return render(request, 'vareaze/profile.html', context)

vareaze/templates/vareaze/base.html
<p>
	{% if not request.user.is_authenticated %}
		<a href="{% url 'vareaze:home' %}">Home</a>
		<a href="{% url 'account:register' %}">Register</a>
		<a href="{% url 'account:authenticate_user' %}">Login</a>
	{% else %}
		<a href="{% url 'vareaze:home' %}">Home</a>
		<a href="{% url 'vareaze:initiate' user.id %}">Contracts</a>
		<a href="{% url 'vareaze:profile' request.user.id %}">Profile</a>
		<a href="{% url 'account:logged_out' %}">Log out</a>	
	{% endif %}
</p>

{% block content %}{% endblock content %}

vareaze/templates/vareaze/contract.html
{% extends 'vareaze/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Contracts</title>
</head>
<body>
	<p>
		{% for account in account_list %}
		{{ account.sent_to }}
		{% empty %}
		{% endfor%}
	</p>
	<p>
		<form action="{% url 'vareaze:initiate' user.id %}" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" name="sign" value="sign">Initiate Request</button>

			
		</form>
			
	</p>
</body>
{% endblock content %}
</html>

vareaze/templates/vareaze/home.html
{% extends 'vareaze/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p>Making lending easier.</p>
	{% for account in accounts %}
		{{ account.username }}<br>
	
	{% empty %}
	{% endfor %}
	{% if user.is_authenticated %}
		<p>Hello, {{ user.vareaze_id }}</p>
	{% else %}
		<p>Not Logged in</p>
	{% endif %}
	{{ user.id }}
</body>
{% endblock content %}
</html>

vareaze/templates/vareaze/profile.html
{% extends 'vareaze/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ user.first_name }} {{ user.last_name }}</title>
</head>
<body>
	<p>{{ user.first_name }} {{ user.last_name }}<br><br>
		{% for contract in contracts %}
			{% if contract.owner.email == request.user.email %}
				{{ contract }}<br>
				{% else %}
			{% endif %}
		{% empty %}
		{% endfor %}

	</p>
</body>
{% endblock content %}
</html>